/*
 * nrf52_pof.h
 *
 *  Created on: 03.01.2021
 *      Author: andru
 */

#ifndef NRF52_POF_H_
#define NRF52_POF_H_

typedef enum {
  POF_V17 = POWER_POFCON_THRESHOLD_V17,
  POF_V18	= POWER_POFCON_THRESHOLD_V18,
  POF_V19	= POWER_POFCON_THRESHOLD_V19,
  POF_V20	= POWER_POFCON_THRESHOLD_V20,
  POF_V21	= POWER_POFCON_THRESHOLD_V21,
  POF_V22	= POWER_POFCON_THRESHOLD_V22,
  POF_V23	= POWER_POFCON_THRESHOLD_V23,
  POF_V24	= POWER_POFCON_THRESHOLD_V24,
  POF_V25	= POWER_POFCON_THRESHOLD_V25,
  POF_V26	= POWER_POFCON_THRESHOLD_V26,
  POF_V27	= POWER_POFCON_THRESHOLD_V27,
  POF_V28	= POWER_POFCON_THRESHOLD_V28,
} nrf52_pof_voltage_t;

extern bool pof_warning;

void pof_init(nrf52_pof_voltage_t v);

#endif /* NRF52_POF_H_ */
